<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caroline Emberson">
<meta name="author" content="Scott Moser">
<meta name="dcterms.date" content="2026-07-11">

<title>Quantifying Hidden Exploitation: Dual-Method Prevalence Estimates of Labour Exploitation among Domestic Workers in the United Kingdom</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript-v7_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript-v7_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript-v7_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript-v7_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript-v7_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript-v7_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript-v7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript-v7_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript-v7_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript-v7_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript-v7_files/libs/bootstrap/bootstrap-c68fc2cee8b264b0f466057160500d73.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-conceptualisation" id="toc-sec-conceptualisation" class="nav-link" data-scroll-target="#sec-conceptualisation"><span class="header-section-number">2</span> Conceptualising Labour Exploitation and the Degree of Risk</a>
  <ul class="collapse">
  <li><a href="#sec-degree-of-risk" id="toc-sec-degree-of-risk" class="nav-link" data-scroll-target="#sec-degree-of-risk"><span class="header-section-number">2.1</span> Evaluating the Degree of Risk</a></li>
  </ul></li>
  <li><a href="#sec-case-setting" id="toc-sec-case-setting" class="nav-link" data-scroll-target="#sec-case-setting"><span class="header-section-number">3</span> Case Setting: Labour Exploitation Risk Among Transnational Migrant Domestic Workers In The UK</a>
  <ul class="collapse">
  <li><a href="#sec-study-design" id="toc-sec-study-design" class="nav-link" data-scroll-target="#sec-study-design"><span class="header-section-number">3.1</span> Study Design and Sampling</a></li>
  <li><a href="#sec-survey-instrument" id="toc-sec-survey-instrument" class="nav-link" data-scroll-target="#sec-survey-instrument"><span class="header-section-number">3.2</span> Survey Instrument and Indicators</a></li>
  <li><a href="#sec-sample-characteristics" id="toc-sec-sample-characteristics" class="nav-link" data-scroll-target="#sec-sample-characteristics"><span class="header-section-number">3.3</span> Sample Characteristics</a></li>
  <li><a href="#sec-estimation-framework" id="toc-sec-estimation-framework" class="nav-link" data-scroll-target="#sec-estimation-framework"><span class="header-section-number">3.4</span> Estimation Framework</a></li>
  <li><a href="#sec-comparative-rationale" id="toc-sec-comparative-rationale" class="nav-link" data-scroll-target="#sec-comparative-rationale"><span class="header-section-number">3.5</span> Comparative Rationale: Ego-Based vs.&nbsp;Alter-Based Inference</a></li>
  <li><a href="#sec-bootstrap" id="toc-sec-bootstrap" class="nav-link" data-scroll-target="#sec-bootstrap"><span class="header-section-number">3.6</span> Bootstrap and Sensitivity Procedures</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-descriptive" id="toc-sec-descriptive" class="nav-link" data-scroll-target="#sec-descriptive"><span class="header-section-number">4.1</span> Descriptive Overview</a>
  <ul class="collapse">
  <li><a href="#sec-rds-diagnostics" id="toc-sec-rds-diagnostics" class="nav-link" data-scroll-target="#sec-rds-diagnostics"><span class="header-section-number">4.1.1</span> RDS Sampling Diagnostics</a></li>
  </ul></li>
  <li><a href="#sec-composite-results" id="toc-sec-composite-results" class="nav-link" data-scroll-target="#sec-composite-results"><span class="header-section-number">4.2</span> Continuous Risk Index: RDS-SS Estimates</a></li>
  <li><a href="#sec-binary-results" id="toc-sec-binary-results" class="nav-link" data-scroll-target="#sec-binary-results"><span class="header-section-number">4.3</span> Binary Exploitation Indicators: Preferred Prevalence Estimates</a></li>
  <li><a href="#sec-supporting-estimates" id="toc-sec-supporting-estimates" class="nav-link" data-scroll-target="#sec-supporting-estimates"><span class="header-section-number">4.4</span> Supporting Estimates and Method Comparison</a></li>
  <li><a href="#sec-sensitivity" id="toc-sec-sensitivity" class="nav-link" data-scroll-target="#sec-sensitivity"><span class="header-section-number">4.5</span> Sensitivity and Robustness</a></li>
  </ul></li>
  <li><a href="#sec-discussion" id="toc-sec-discussion" class="nav-link" data-scroll-target="#sec-discussion"><span class="header-section-number">5</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary"><span class="header-section-number">5.1</span> Summary of Findings</a></li>
  <li><a href="#sec-contributions" id="toc-sec-contributions" class="nav-link" data-scroll-target="#sec-contributions"><span class="header-section-number">5.2</span> Methodological Reflections and Contributions</a></li>
  <li><a href="#sec-divergence" id="toc-sec-divergence" class="nav-link" data-scroll-target="#sec-divergence"><span class="header-section-number">5.3</span> The RDS–NSUM Divergence as Diagnostic</a></li>
  <li><a href="#sec-generalisability" id="toc-sec-generalisability" class="nav-link" data-scroll-target="#sec-generalisability"><span class="header-section-number">5.4</span> Generalisability and Indicator Coverage</a></li>
  <li><a href="#sec-weights-sensitivity" id="toc-sec-weights-sensitivity" class="nav-link" data-scroll-target="#sec-weights-sensitivity"><span class="header-section-number">5.5</span> Composite Risk Index: Construction and Weight Sensitivity</a></li>
  <li><a href="#sec-policy" id="toc-sec-policy" class="nav-link" data-scroll-target="#sec-policy"><span class="header-section-number">5.6</span> Policy Implications and SDG 8.7 Monitoring</a></li>
  </ul></li>
  <li><a href="#sec-conclusion" id="toc-sec-conclusion" class="nav-link" data-scroll-target="#sec-conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  <li><a href="#sec-declarations" id="toc-sec-declarations" class="nav-link" data-scroll-target="#sec-declarations"><span class="header-section-number">7</span> Declarations</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript-v7.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="manuscript-v7.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quantifying Hidden Exploitation: Dual-Method Prevalence Estimates of Labour Exploitation among Domestic Workers in the United Kingdom</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Caroline Emberson </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Nottingham
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Scott Moser </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Nottingham
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">11 July 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Reliable indicators for SDG Target 8.7 are difficult to construct because the populations most affected by labour exploitation are often absent from standard household and labour-force surveys. This paper develops a matched ego/alter survey design for measuring labour exploitation among hidden populations. We apply respondent-driven sampling and a network scale-up approach to the same survey instrument, asking migrant domestic workers in the United Kingdom both about their own experiences and about exploitation among domestic workers they know. The design produces two complementary estimands: own-experience prevalence and network-visible prevalence. We measure five ILO-aligned indicators: excessive working hours, pay-related issues, limited access to help, threats and abuse, and document withholding. We also construct a formative composite risk index to capture gradations of exploitation severity. In a civil-society-mediated web-RDS sample of 85 migrant domestic workers, RDS-SS estimates indicate high own-experience prevalence, while network scale-up estimates are substantially lower. The divergence is consistent with a visibility gradient in which some exploitation behaviours are more observable across peer networks than others. The results should be interpreted as exploratory population-adjusted estimates for an RDS-reachable population rather than definitive national prevalence figures. The relative ordering of prevalence of different forms of labour exploitation are robust across a number of parameters. The paper contributes a replicable measurement design for hidden-population social indicators relevant to SDG 8.7 monitoring.</p>
  </div>
</div>


</header>


<!--
MANUSCRIPT v5 (2026-06-30)

Canonical source for SIR submission. v4 fixes two production-level issues
Scott reported in the rendered v3 PDF:

  1. Broken Quarto cross-references appeared as '?@tbl-X' / '?@fig-X'.
     Fixed by switching to plain-text references throughout: '@fig-recruitment',
     '@fig-rds-diagnostics', ..., '@tbl-indicator-mapping', '@tbl-sample-chars', ..., '@tbl-preferred-estimates'. All Quarto
     {#fig-X} and {#tbl-X} labels removed. Sequential numbering matches
     document order.

  2. Doubled caption prefixes ('@fig-recruitment: @fig-recruitment...', '@tbl-sample-chars:
     @tbl-indicator-mapping...') because manual prefix + Quarto auto-numbering collided.
     Fixed by removing Quarto labels so it doesn't auto-number; manual
     'Figure N. ' / 'Table N. ' prefixes now provide the only numbering
     and match the body-text references.

  3. @tbl-indicator-mapping (indicator mapping) grid table was rendering with
     overlapping text in the PDF. Converted to a pipe table for
     reliable rendering. Tables 3 and 4 (estimands, RDS diagnostics)
     remain as grid tables — flagged in case they also need conversion.

Sections that did NOT exist in v3 as separately-numbered items:
  - 'Table M' / 'Table E' / 'Table D' mnemonic labels (now Tables 1, 3, 4
    by document order).

DEFERRED (still TODO per Scott):
  - Anonymise GitHub repo path + 'lead author's School Research Ethics
    Committee' language for double-anonymous review.
  - Insert anonymised OSF view-only URL (@sec-estimation-framework placeholder).

Render commands (run on Scott's machine):
  quarto render manuscript-v4.qmd                # all formats
  quarto render manuscript-v4.qmd --to docx      # Word only
  quarto render manuscript-v4.qmd --to pdf       # PDF (needs LaTeX)
-->
<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Modern slavery – defined in UK law as an umbrella term which includes slavery, servitude, forced labour, and human trafficking – is named under Sustainable Development Goal Target 8.7 as a priority for elimination by 2030. Reliable prevalence measurement is a precondition for monitoring that target, yet the populations most affected are largely invisible to the household and labour-force surveys on which official social indicators rely. Conventional household surveys underestimate prevalence in this domain by an order of magnitude or more, both because the populations affected (undocumented migrants, live-in domestic workers, sex workers, agricultural day labourers) are excluded from sampling frames, and because exploitation behaviours – especially those at the more severe end of the spectrum – are typically not self-reported even when the respondent is contacted. The civil-society and grey-literature evidence base on UK domestic workers <span class="citation" data-cites="kala08-new serv23-closed">(<a href="#ref-kala08-new" role="doc-biblioref">Kalayaan, 2008</a>; <a href="#ref-serv23-closed" role="doc-biblioref">Service, 2023</a>)</span> is qualitatively rich but does not yield population-level prevalence estimates suitable for SDG monitoring or comparison across populations. The International Labour Organization’s eleven indicators of forced labour <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> provide an operational framework for measuring modern slavery, but the empirical question of which indicators are observable through which survey design remains open. Studies typically apply one design – household survey, respondent-driven sampling (RDS), or the network scale-up method (NSUM) – and report prevalence accordingly. No prior study of modern-slavery prevalence, to our knowledge, applies both RDS and NSUM to a single matched survey instrument. Such a design would enable direct triangulation of ego- and alter-based estimates on identical indicators and, where they diverge, diagnostic inference about which exploitation behaviours are visible across personal networks.</p>
<p>This paper makes two contributions. First, we apply RDS and NSUM to the same survey instrument with the same respondents, eliciting ego-based and alter-based estimates of an identical set of five ILO-aligned indicators. The dual-method design produces two complementary estimands (own-experience prevalence from RDS, network-visible prevalence from NSUM); where they diverge, the gap itself is diagnostic evidence about the visibility gradient of different exploitation behaviours within workers’ personal networks. Second, we treat modern slavery as a graded phenomenon rather than a binary condition. The ILO’s eleven indicators of forced labour <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> anchor the operational framework, and the ILO’s survey-guidelines handbook <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span> distinguishes three ‘strong’ indicators (retention of identity documents, intimidation and threats, and physical and sexual violence) — any one of which is generally sufficient to identify forced labour in survey settings — from eight ‘medium’ indicators, several of which typically need to co-occur. The ordering supports both indicator-level prevalence estimates and a composite risk index. Taken together, the contribution of the paper is best read as developing and demonstrating a defensible social-indicator measurement strategy for hidden-population exploitation rather than as producing a definitive national prevalence estimate. We demonstrate the strategy with a respondent-driven sample of UK migrant domestic workers and discuss how the methodology generalises to other hidden populations relevant to SDG 8.7 monitoring.</p>
<p>The remainder of the paper is organised as follows. <a href="#sec-conceptualisation" class="quarto-xref">Section&nbsp;2</a> conceptualises labour exploitation as a graded formative indicator framework measured by five ILO-aligned indicators arranged hierarchically by severity. <a href="#sec-case-setting" class="quarto-xref">Section&nbsp;3</a> describes the matched-instrument survey design (<a href="#sec-study-design" class="quarto-xref">Section&nbsp;3.1</a>) and the dual sampling approach combining RDS and NSUM (<a href="#sec-survey-instrument" class="quarto-xref">Section&nbsp;3.2</a>). <a href="#sec-results" class="quarto-xref">Section&nbsp;4</a> presents prevalence estimates by indicator and method, including frequentist RDS-I/RDS-II/RDS-SS estimators (<a href="#sec-descriptive" class="quarto-xref">Section&nbsp;4.1</a>), Bayesian Model-Assisted inference (<a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>), and NSUM with sensitivity analysis (<a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a>). <a href="#sec-discussion" class="quarto-xref">Section&nbsp;5</a> reads the RDS-NSUM divergence as diagnostic evidence about visibility within workers’ personal networks and discusses implications for SDG 8.7 monitoring.</p>
</section>
<section id="sec-conceptualisation" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Conceptualising Labour Exploitation and the Degree of Risk</h1>
<p>The International Labour Organization’s eleven indicators of forced labour <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> provide the canonical operational framework for measuring modern slavery. The ILO’s own survey-guidelines handbook <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span> distinguishes two operational categories for use in forced-labour surveys: ‘strong’ indicators (intimidation and threats, physical and sexual violence, retention of identity documents) any one of which is generally sufficient on its own to identify a survey respondent as in forced labour, and ‘medium’ indicators (excessive overtime, wage withholding, debt bondage, restriction of movement, isolation, abusive working and living conditions, abuse of vulnerability, deception) whose evidentiary weight for survey-based identification typically requires more than one to be present. We adopt this severity ordering — as it appears in the ILO survey-guidelines handbook rather than the shorter operational-indicators publications <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span>, which list the eleven without ranking them — to organise the reporting of the five binary indicators below and to structure the reporting of the composite risk index. We measure five indicators across the ordering, chosen to span the ILO conceptual space efficiently within the constraints of a matched-instrument ego/alter survey design. Three are medium indicators – excessive working hours, pay-related issues (combining wage withholding with elements of debt bondage), and limited access to help (combining restriction of movement with isolation, as both manifest in the same observable behaviour in the domestic-work context). Two are strong indicators – threats and abuse (combining intimidation/threats with physical and sexual violence, which prior qualitative work suggests co-occur in this population: <span class="citation" data-cites="yilm23-exploring">Yilmaz &amp; Emberson (<a href="#ref-yilm23-exploring" role="doc-biblioref">2023</a>)</span>) and document and passport withholding. The specific bundling of ILO indicators into these five binary measures (e.g., combining intimidation/threats with physical and sexual violence into a single ‘threats and abuse’ indicator) is our analytical choice, informed by the qualitative and civil-society literature on UK migrant domestic workers <span class="citation" data-cites="kala08-new mant16-modern serv23-closed yilm23-exploring">(<a href="#ref-kala08-new" role="doc-biblioref">Kalayaan, 2008</a>; <a href="#ref-mant16-modern" role="doc-biblioref">Mantouvalou, 2016</a>; <a href="#ref-serv23-closed" role="doc-biblioref">Service, 2023</a>; <a href="#ref-yilm23-exploring" role="doc-biblioref">Yilmaz &amp; Emberson, 2023</a>)</span>, not a mapping the ILO itself publishes. The remaining two ILO indicators – abuse of vulnerability and deception – are not measured as standalone binary prevalence indicators: both are too retrospective and judgemental to elicit reliably through a brief survey of n=85 respondents (the respondent would need to reconstruct intent and knowledge states from the perspective of months or years after the fact). Both are nonetheless included in the composite risk index (Appendix Table A.1, Categories 1 and 2; results in <a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>). Where appropriate we note this scope limitation in the discussion of results.</p>
<p>The composite risk index aggregates all eleven ILO indicators of forced labour into a single continuous measure (<a href="#sec-survey-instrument" class="quarto-xref">Section&nbsp;3.2</a>, <a href="#tbl-indicator-mapping" class="quarto-xref">Table&nbsp;1</a>; Appendix Table A.1 for per-category weights). It is constructed as a formative additive composite: an individual is exposed to exploitation if any of the indicators is present, and the indicators are constitutive rather than reflective of an underlying severity. We conduct robustness assessment by perturbing the weights (<a href="#sec-weights-sensitivity" class="quarto-xref">Section&nbsp;5.5</a>). Two further evidentiary markers, NRM-referral history and payment below the national living wage, are reported as separate binary flags and are not part of the composite, as their direct evidentiary status under UK policy makes them more useful read independently.</p>
<section id="sec-degree-of-risk" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-degree-of-risk"><span class="header-section-number">2.1</span> Evaluating the Degree of Risk</h2>
<p>We conceptualise risk of labour exploitation from the workers’ perspective, spanning a spectrum from illegal employment practices (below-minimum-wage payment, health and safety violations) through to forced labour and modern slavery. The more ILO indicators present, the stronger the likelihood of exploitation. We operationalise this in two complementary ways: binary indicators classifying respondents as exploited or not on each ILO-aligned dimension (threshold criteria, <a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a>) and a continuous formative additive composite risk index capturing gradations of vulnerability across all eleven ILO indicators (<a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>; the Appendix, Section A, for full construction).</p>
</section>
</section>
<section id="sec-case-setting" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Case Setting: Labour Exploitation Risk Among Transnational Migrant Domestic Workers In The UK</h1>
<p>Domestic work in the United Kingdom is performed predominantly by transnational migrant women, the majority entering on tied Overseas Domestic Worker (ODW) visas under which the right to remain is conditional on employment with a specific employer <span class="citation" data-cites="mant16-modern kala08-new serv23-closed">(<a href="#ref-kala08-new" role="doc-biblioref">Kalayaan, 2008</a>; <a href="#ref-mant16-modern" role="doc-biblioref">Mantouvalou, 2016</a>; <a href="#ref-serv23-closed" role="doc-biblioref">Service, 2023</a>)</span>. The combination of tied immigration status, work performed inside the private home, and the absence of routine workplace inspection creates structural conditions under which labour exploitation can occur unobserved by employment regulators, mainstream labour-market surveys, and the police <span class="citation" data-cites="romero_blueprint_2025">(<a href="#ref-romero_blueprint_2025" role="doc-biblioref">Romero &amp; Fisher, 2025</a>)</span>. Civil-society organisations representing migrant domestic workers have documented patterns of wage withholding, document confiscation, restricted movement, excessive working hours, and threats and abuse over more than two decades <span class="citation" data-cites="kala08-new mant16-modern serv23-closed yilm23-exploring">(<a href="#ref-kala08-new" role="doc-biblioref">Kalayaan, 2008</a>; <a href="#ref-mant16-modern" role="doc-biblioref">Mantouvalou, 2016</a>; <a href="#ref-serv23-closed" role="doc-biblioref">Service, 2023</a>; <a href="#ref-yilm23-exploring" role="doc-biblioref">Yilmaz &amp; Emberson, 2023</a>)</span>. However, qualitative and case-based evidence have not yielded population-level prevalence estimates suitable for SDG 8.7 monitoring or cross-population comparison. The UK migrant domestic worker case is therefore well-suited as the testbed for a measurement methodology aimed at producing comparable prevalence indicators for hidden, civil-society-mediated populations relevant to SDG 8.7 reporting. The methodology demonstrated here generalises to other hidden populations sharing the structural features of tied employment, private-home workplaces, and civil-society-mediated access.</p>
<section id="sec-study-design" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-study-design"><span class="header-section-number">3.1</span> Study Design and Sampling</h2>
<p>Respondent-Driven Sampling (RDS) is a network-based sampling method designed to study hidden or hard-to-reach populations <span class="citation" data-cites="heck97-respondentdriven heck11-comment gile18-methods">(<a href="#ref-gile18-methods" role="doc-biblioref">Gile et al., 2018</a>; <a href="#ref-heck97-respondentdriven" role="doc-biblioref">Heckathorn, 1997</a>; <a href="#ref-heck11-comment" role="doc-biblioref">Heckathorn, 2011</a>)</span>. It combines chain-referral sampling with a statistical framework to produce population estimates that adjust for network structure and differential recruitment probabilities. The method begins with a set of initial participants (“seeds”), who recruit peers from their social networks. Recruits, in turn, recruit others, creating waves of participation. The number of each participant’s recruits implicitly proxies for their network degree (the number of eligible contacts they know), which is used to adjust for selection bias–especially the oversampling of high-degree individuals.</p>
<p>RDS has been widely used to sample hidden populations in public health and social science research <span class="citation" data-cites="mccr12-evaluation schw12-prevalence">(<a href="#ref-mccr12-evaluation" role="doc-biblioref">McCreesh et al., 2012</a>; <a href="#ref-schw12-prevalence" role="doc-biblioref">Schwitters et al., 2012</a>)</span>, and network-based referrals have been described as the only viable method to reach many types of labour trafficking victims <span class="citation" data-cites="zhang_measuring_2012">(<a href="#ref-zhang_measuring_2012" role="doc-biblioref">Zhang, 2012</a>)</span>. Recent applications include studies of exploitation among low-wage workers in American cities <span class="citation" data-cites="bern09-broken">(<a href="#ref-bern09-broken" role="doc-biblioref">Bernhardt et al., 2009</a>)</span>, labour trafficking in migrant communities <span class="citation" data-cites="vinc17-estimating">(<a href="#ref-vinc17-estimating" role="doc-biblioref">Vincent &amp; Thompson, 2017</a>)</span>, child labour in India <span class="citation" data-cites="zhan19-victims">(<a href="#ref-zhan19-victims" role="doc-biblioref">Zhang et al., 2019</a>)</span>, and commercial sexual exploitation in Nepal <span class="citation" data-cites="jord20-overcoming">(<a href="#ref-jord20-overcoming" role="doc-biblioref">Jordan et al., 2020</a>)</span>.</p>
<p>Our approach can best be described as Web-based RDS <span class="citation" data-cites="wejn08-webbased">(<a href="#ref-wejn08-webbased" role="doc-biblioref">Wejnert &amp; Heckathorn, 2008</a>)</span>. We designed a web survey using the JISC online survey interface, suitable for respondents to complete via mobile phone. The main survey was conducted over five months between February and July 2023.</p>
<p><em>Seed Selection and Recruitment</em></p>
<p>We selected our first wave of participants nonrandomly by convenience sampling. Mobile phone numbers were used both to identify seed participants and to act as a unique identifier for those whom they referred. To avoid sample homophily, original sample members were selected from three distinct domestic worker communities facilitated by civil society organisations. One was an exclusively online community of transnational domestic workers working in the UK, the second represented UK domestic workers of Filipino origin, and the third drew its membership from the Latin American community of domestic workers, also in the UK. Representatives from these organisations, along with other academics with expertise in exploitation within domestic work, contributed to survey question design and facilitated piloting of an initial version of the survey, which was translated and made available in four languages: English, Spanish, Tagalog, and Portuguese.</p>
<p><em>Incentive Design and Participation Verification</em></p>
<p>A double incentive scheme rewarded respondents both for completing the questionnaire and for each referral who went on to engage with the survey. The challenge of incentive design is to set the incentive at a level that adequately rewards respondents’ time and participation, but that also avoids the risk of fraudulent participation due to too high a monetary gain <span class="citation" data-cites="jord20-overcoming">(<a href="#ref-jord20-overcoming" role="doc-biblioref">Jordan et al., 2020</a>)</span>. A sum of £10 was provided for survey completion with a further £5 for each successful nomination. While respondents were asked to nominate up to 10 domestic workers within their existing social network, participation from up to five of these was requested in subsequent waves. This approach is akin to the use of vouchers in face-to-face studies as advocated by <span class="citation" data-cites="thompson_new_2020">Thompson (<a href="#ref-thompson_new_2020" role="doc-biblioref">2020</a>)</span>.</p>
<p>Respondents were incentivised through lottery entry, consistent with the design recommendations of the survey-incentive literature (full literature review and incentive-design details in the Appendix, Section D.7).</p>
</section>
<section id="sec-survey-instrument" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-survey-instrument"><span class="header-section-number">3.2</span> Survey Instrument and Indicators</h2>
<p>The survey instrument was designed to capture both egocentric (ego-based) and altercentric (alter-based) network information, enabling the application of both RDS and NSUM estimation methods. Composite measures to quantify the extent to which respondents were at risk of labour exploitation, including severe forms of exploitation such as forced labour, were constructed from existing exploitation typologies, notably the ILO’s Indicators of Forced Labour <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> and the associated survey-guidelines handbook <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span>. The eleven ILO indicators of forced labour <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> provide the operational framework for our measurement strategy; the medium/strong severity ordering used to organise the indicators follows the ILO handbook on forced-labour surveys <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span>. <a href="#tbl-indicator-mapping" class="quarto-xref">Table&nbsp;1</a> (below) maps each ILO indicator to its measurement status in this paper: whether it is measured directly as a binary prevalence indicator (reported in <a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a>), whether it is included in the formative additive composite risk index (reported in <a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>), and which survey questions elicit the ego- and alter-based reports.</p>
<div id="tbl-indicator-mapping" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-indicator-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Mapping of the eleven ILO Indicators of Forced Labour to this paper’s measurement scheme. The five binary prevalence indicators (right-hand grouping in column 4: document withholding, threats and abuse, pay-related issues, limited access to help, excessive working hours) jointly cover nine of the eleven ILO indicators (all except abuse of vulnerability and deception, which are captured in the composite only). The composite risk index covers all eleven ILO indicators through eleven weighted sub-categories. Two further evidentiary markers – NRM-referral history (Q80) and payment below the national living wage (Q36) – are reported as separate binary flags and are not part of the composite. The medium/strong severity classification in column 2 follows the ILO handbook on forced-labour surveys <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span>; the shorter operational-indicators publications <span class="citation" data-cites="ILO11-indicators int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">International Labour Organization, 2012</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span> list the eleven indicators without publishing this severity ranking. Full per-category weight values are given in Appendix Table A.1. Source: Authors’ construction following ILO <span class="citation" data-cites="ILO11-indicators hard24-ilo int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">2012</a>, <a href="#ref-hard24-ilo" role="doc-biblioref">2024</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span>.
</figcaption>
<div aria-describedby="tbl-indicator-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 34%">
<col style="width: 10%">
<col style="width: 23%">
<col style="width: 10%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">#</th>
<th style="text-align: left;">ILO indicator (2012, 2017)</th>
<th style="text-align: center;">Severity</th>
<th style="text-align: left;">Binary indicator</th>
<th style="text-align: center;">Composite</th>
<th style="text-align: left;">Survey item(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Abuse of vulnerability</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">– (composite only)</td>
<td style="text-align: center;">Cat 1</td>
<td style="text-align: left;">Q29, Q51</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Deception</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">– (composite only)</td>
<td style="text-align: center;">Cat 2</td>
<td style="text-align: left;">Q45</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Restriction of movement</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Limited access to help</td>
<td style="text-align: center;">Cat 3</td>
<td style="text-align: left;">Q32, Q46</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Isolation</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Limited access to help</td>
<td style="text-align: center;">Cat 4</td>
<td style="text-align: left;">Q65</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Physical and sexual violence</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: left;">Threats and abuse</td>
<td style="text-align: center;">Cat 5</td>
<td style="text-align: left;">Q44 (5c1, 5c1-b)</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Intimidation and threats</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: left;">Threats and abuse</td>
<td style="text-align: center;">Cat 6</td>
<td style="text-align: left;">Q47</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Retention of identity documents</td>
<td style="text-align: center;">Strong</td>
<td style="text-align: left;">Document withholding</td>
<td style="text-align: center;">Cat 7</td>
<td style="text-align: left;">Q70</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Withholding of wages</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Pay-related issues</td>
<td style="text-align: center;">Cat 8</td>
<td style="text-align: left;">Q42</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Debt bondage</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Pay-related issues</td>
<td style="text-align: center;">Cat 9</td>
<td style="text-align: left;">Q39</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Abusive working and living conditions</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Partial (Q48)</td>
<td style="text-align: center;">Cat 10</td>
<td style="text-align: left;">Q48, Q63, Q72, Q76</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Excessive overtime</td>
<td style="text-align: center;">Medium</td>
<td style="text-align: left;">Excessive working hours</td>
<td style="text-align: center;">Cat 11</td>
<td style="text-align: left;">Q16, Q61, Q62</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Based on this mapping, we operationalise exploitation in two ways: (1) five binary prevalence indicators classifying respondents as exploited or not exploited on each dimension based on threshold criteria (<a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a>), and (2) one continuous formative additive composite risk index designed to capture gradations of vulnerability across the full sample (<a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>).</p>
<p>Ego-based questions capture respondents’ own experiences of exploitation (used for RDS estimation), while alter-based questions ask respondents to report on the exploitation experiences of domestic workers they know (used for NSUM estimation). See the Appendix (Sections A and B) for details of these survey questions and the construction of comparable ego- and alter-based indicators.</p>
</section>
<section id="sec-sample-characteristics" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-sample-characteristics"><span class="header-section-number">3.3</span> Sample Characteristics</h2>
<p>In total, we received completed online surveys from 97 respondents. Twelve participants reported knowing zero domestic workers in the UK and were excluded from RDS analysis because network degree information is required for RDS weighting procedures. This resulted in an analytical sample of 85 respondents for RDS-based estimation. Although the analytic sample comprises 85 respondents, this is within the range used in comparable respondent-driven sampling (RDS) and network scale-up (NSUM) studies of hidden populations <span class="citation" data-cites="gile10-respondentdriven goel10-assessing gile11-improved">(<a href="#ref-gile11-improved" role="doc-biblioref">Gile, 2011</a>; <a href="#ref-gile10-respondentdriven" role="doc-biblioref">Gile &amp; Handcock, 2010</a>; <a href="#ref-goel10-assessing" role="doc-biblioref">Goel &amp; Salganik, 2010</a>)</span>. Statistical inference in these designs depends not on the absolute sample size but on the structure of the recruitment network, degree distribution, and convergence to equilibrium <span class="citation" data-cites="salg04-sampling">(<a href="#ref-salg04-sampling" role="doc-biblioref">Salganik &amp; Heckathorn, 2004</a>)</span>. Furthermore, model-assisted and Bayesian RDS estimators <span class="citation" data-cites="gile11-improved gile18-methods">(<a href="#ref-gile11-improved" role="doc-biblioref">Gile, 2011</a>; <a href="#ref-gile18-methods" role="doc-biblioref">Gile et al., 2018</a>)</span> can produce model-assisted, population-adjusted estimates under explicit assumptions, even in modest samples, provided uncertainty and design limitations are made transparent. In this study, we additionally employ a neighbourhood bootstrap procedure that propagates sampling and network uncertainty, providing robust confidence intervals consistent with small-sample design-based inference <span class="citation" data-cites="hand14-estimating">(<a href="#ref-hand14-estimating" role="doc-biblioref">Handcock et al., 2014</a>)</span>.</p>
<p>Of the 97 initial respondents, 90 identified themselves as transnational migrants. In the analytical sample of <span class="math inline">\(n = 85\)</span> (<a href="#tbl-demographics" class="quarto-xref">Table&nbsp;2</a>), 47% regarded themselves as self-employed, 37% identified themselves as employees, and 17% categorised their employment status as agency workers. Filipino respondents constitute the largest nationality cluster (65 respondents, 76% of the analytical sample; <a href="#tbl-sample-chars" class="quarto-xref">Table&nbsp;3</a> for the full nationality × wave breakdown); other nationalities represented include Dominican, Brazilian, Spanish, Colombian, Bolivian, Venezuelan, Cuban, and Panamanian. Female domestic workers made up 98% of the analytical sample, with the remaining 2% male. The age structure is skewed towards older workers: 49% of respondents are aged 45+, and a further 26% are aged 35–40 (<a href="#tbl-demographics" class="quarto-xref">Table&nbsp;2</a>).</p>
<div id="fig-recruitment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-recruitment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1_recruitment_network.png" class="img-fluid figure-img" style="width:6in">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-recruitment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: RDS Recruitment Network Structure. Recruitment chains showing seed nodes (triangles) and recruit nodes (circles). Node colours represent nationality clusters; node size is proportional to network degree. Lines show recruiter-recruit relationships. Source: Authors’ own work.
</figcaption>
</figure>
</div>
<div id="tbl-demographics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-demographics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Sample demographics (n = 85 analytical sample). Response categories for age and length of time in the UK follow the survey codebook (Appendix A.3); the codebook’s original response options include a small ordinal gap between 40 and 45 years of age. Source: Authors’ construction from <code>data/processed/prepared_data.csv</code>.
</figcaption>
<div aria-describedby="tbl-demographics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Characteristic</th>
<th style="text-align: left;">Category</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Gender</strong></td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">97.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Age</strong></td>
<td style="text-align: left;">23–25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">26–35</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">23.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">35–40</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">25.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">45+</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">49.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Employment status</strong></td>
<td style="text-align: left;">Self-employed</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">47.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Employee</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">36.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Agency worker</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">16.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Length of time in UK</strong></td>
<td style="text-align: left;">Less than 3 months</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3 months to 1 year</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">22.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1 to 3 years</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">16.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">More than 3 years</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">57.6%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-sample-chars" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sample-chars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Sample composition by nationality cluster and recruitment wave (n = 85). Wave 0 indicates seed respondents; subsequent waves are respondent-driven recruits. Filipino respondents dominate the sample (76%) and contribute the deepest recruitment chains; other nationality clusters are smaller and shallower. Source: Authors’ own work.
</figcaption>
<div aria-describedby="tbl-sample-chars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nationality cluster</th>
<th style="text-align: right;">Wave 0 (seeds)</th>
<th style="text-align: right;">Wave 1</th>
<th style="text-align: right;">Wave 2</th>
<th style="text-align: right;">Wave 3+</th>
<th style="text-align: right;">Total (n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Filipino</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Latinx</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">British</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>46</strong></td>
<td style="text-align: right;"><strong>25</strong></td>
<td style="text-align: right;"><strong>11</strong></td>
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><strong>85</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-estimation-framework" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-estimation-framework"><span class="header-section-number">3.4</span> Estimation Framework</h2>
<p>Before describing each estimator in turn, <a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a> summarises the information each method uses, the population quantity each method targets (its <em>estimand</em>), and the principal source of identification risk for each. The four estimators do not target the same quantity. RDS-SS and MA-RDS estimate own-experience prevalence among the RDS-reachable population of migrant domestic workers; NSUM estimates network-visible prevalence among domestic-worker alters as reported by the respondent; the composite risk index targets the RDS-adjusted mean severity score. The order-of-magnitude RDS–NSUM gap should not be read as two methods disagreeing about the same estimand. RDS estimates own-experience prevalence, whereas NSUM estimates network-visible prevalence among alters; the divergence is therefore substantively interpretable rather than merely a discrepancy.</p>
<div id="tbl-estimands" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-estimands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Estimands and identification vulnerabilities of the four estimators applied in this paper. Each row characterises one estimator: what information from the survey it uses, what population quantity it targets, and what the principal threat to identification is. Source: Authors’ construction.
</figcaption>
<div aria-describedby="tbl-estimands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 27%">
<col style="width: 29%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Information used</th>
<th style="text-align: left;">Estimand</th>
<th style="text-align: left;">Main vulnerability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RDS-SS (binary, preferred)</td>
<td style="text-align: left;">Respondent’s own experience + reported degree + recruitment-chain structure</td>
<td style="text-align: left;">Own-experience prevalence among the RDS-reachable population of UK migrant domestic workers</td>
<td style="text-align: left;">Seed dependence, shallow recruitment chains, homophily, unobserved degree heterogeneity</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA-RDS (supporting)</td>
<td style="text-align: left;">Same as RDS-SS, plus a working Exponential Random Graph network model</td>
<td style="text-align: left;">Model-assisted own-experience prevalence (same target as RDS-SS, with network-structure adjustment)</td>
<td style="text-align: left;">Network-model misspecification, convergence limits at small <span class="math inline">\(n\)</span>; does not converge on continuous outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MBSU NSUM (binary, preferred)</td>
<td style="text-align: left;">Respondent reports about alters in their personal network</td>
<td style="text-align: left;">Network-visible prevalence among domestic-worker alters in the respondents’ aggregated network</td>
<td style="text-align: left;">Transmission bias, visibility gradient across exploitation behaviours, alter misclassification, unknown true-positive rate (<span class="math inline">\(\tau\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite risk index</td>
<td style="text-align: left;">Respondent’s own indicator profile across all eleven ILO indicators</td>
<td style="text-align: left;">RDS-adjusted population mean of the formative-additive severity score</td>
<td style="text-align: left;">Weight specification, construct validity, formative-vs-reflective measurement assumptions</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To the best of the authors’ knowledge, the combined use of both methods in the same study is rare in peer-reviewed academic research, though it has appeared in government-funded reports and technical documents from NGOs and research organizations <span class="citation" data-cites="ist20-prevalence hick25-human">(<a href="#ref-hick25-human" role="doc-biblioref">Hickman et al., 2025</a>; <a href="#ref-ist20-prevalence" role="doc-biblioref">IST Research &amp; University of California, Los Angeles, 2020</a>)</span>. This paper contributes to the emerging methodological literature on combining RDS and NSUM in survey research for hidden populations. We also developed a novel three-step bootstrap procedure to address uncertainty in NSUM estimates.</p>
<p><em>RDS Estimation:</em> We implemented three RDS estimators, each with distinct assumptions: RDS-I <span class="citation" data-cites="salg04-sampling">(<a href="#ref-salg04-sampling" role="doc-biblioref">Salganik &amp; Heckathorn, 2004</a>)</span>, the Volz–Heckathorn (VH) estimator <span class="citation" data-cites="volz08-probability">(<a href="#ref-volz08-probability" role="doc-biblioref">Volz &amp; Heckathorn, 2008</a>)</span>, and Gile’s Successive Sampling (RDS-SS) estimator <span class="citation" data-cites="gile11-improved">(<a href="#ref-gile11-improved" role="doc-biblioref">Gile, 2011</a>)</span>. Given our small sample (85 respondents) and non-negligible sampling fraction, RDS-SS serves as our primary estimator for binary outcomes because it accounts for finite population effects. RDS-I, which performs poorly in small samples and is highly sensitive to seed dependence, is retained as a historical benchmark.</p>
<p>For continuous outcomes such as the exploitation risk index, we employ Model-Assisted (MA-RDS) estimators <span class="citation" data-cites="gile15-network">(<a href="#ref-gile15-network" role="doc-biblioref">Gile &amp; Handcock, 2015</a>)</span>. MA-RDS is design-based yet leverages a working Exponential Random Graph Model (ERGM) with degree and homophily terms to approximate inclusion probabilities conditional on observed seeds. This approach directly addresses seed bias and homophily that conventional RDS estimators cannot correct, accommodates finite-population effects through successive-sampling logic, and supports valid estimation of both binary and continuous outcomes. By conditioning on actual seed composition and subgroup structure, the method reduces bias, improves efficiency, and provides design-compatible bootstrap uncertainty <span class="citation" data-cites="gile11-improved">(<a href="#ref-gile11-improved" role="doc-biblioref">Gile, 2011</a>)</span>. We note one important limitation: the MA-RDS implementation in the <code>RDS</code> package (<code>MA.estimates()</code>) is designed primarily for binary traits, and we find that for the continuous composite risk index it does not converge to a useful posterior at our sample size (<span class="math inline">\(n=85\)</span>); the credible interval covers essentially the full support of the variable. We therefore report frequentist RDS-SS estimates as the headline for the composite index and reserve MA-RDS estimates for the five binary indicators (see <a href="#sec-supporting-estimates" class="quarto-xref">Section&nbsp;4.4</a> and the Appendix D.2).</p>
<p><em>Within-Population Scale-Up Estimation (NSUM):</em> We employ the Modified Basic Scale-Up (MBSU) logic of <span class="citation" data-cites="feeh16-generalizing">Feehan &amp; Salganik (<a href="#ref-feeh16-generalizing" role="doc-biblioref">2016</a>)</span> in a non-standard, within-population configuration. In standard NSUM, respondents are usually sampled from a frame population and report how many people they know in a hidden population. Here, by contrast, respondents are themselves UK migrant domestic workers and report on other UK migrant domestic workers they know. We therefore treat the design as a <em>within-population scale-up</em> or <em>alter-report network prevalence</em> design: the target quantity is not the absolute size of the hidden population, but the network-visible prevalence of exploitation indicators among domestic-worker alters in respondents’ personal networks. This estimand differs from the standard NSUM estimand and is documented in <a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a> above.</p>
<p>Let <span class="math inline">\(H_h\)</span> denote the subset of domestic-worker alters who truly have exploitation indicator <span class="math inline">\(h\)</span>, and let <span class="math inline">\(F\)</span> denote the domestic-worker alter universe induced by the survey’s tie definition (the <em>frame</em>). For respondent <span class="math inline">\(i\)</span>, let <span class="math inline">\(y_{ih}\)</span> be the reported number of known domestic-worker alters with indicator <span class="math inline">\(h\)</span>, and let <span class="math inline">\(d_i^{DW}\)</span> be respondent <span class="math inline">\(i\)</span>’s reported number of known UK migrant domestic workers. The quantity <span class="math inline">\(d_i^{DW}\)</span> is therefore a domestic-worker alter degree: it is the denominator for the alter reports <span class="math inline">\(y_{ih}\)</span>, not respondent <span class="math inline">\(i\)</span>’s total personal network size in the usual NSUM sense.</p>
<p>The unadjusted within-population NSUM estimator is</p>
<p><span id="eq-1"><span class="math display">\[
\hat p_h^{NSUM} = \frac{\sum_i w_i y_{ih}}{\sum_i w_i d_i^{DW}},
\tag{1}\]</span></span></p>
<p>where <span class="math inline">\(w_i\)</span> is the RDS-derived survey weight. This estimator is a weighted alter-level proportion: it estimates the share of reported domestic-worker alters who are reported to have indicator <span class="math inline">\(h\)</span>. It should therefore be interpreted as a measure of <em>network-visible prevalence</em> among domestic-worker alters, rather than as a direct estimate of own-experience prevalence among respondents.</p>
<p>The MBSU-adjusted prevalence is then</p>
<p><span id="eq-2"><span class="math display">\[
\hat p_h^{MBSU} =
\frac{1}{\delta_h \tau_h}
\frac{\sum_i w_i y_{ih}}{\sum_i w_i d_i^{DW}}.
\tag{2}\]</span></span></p>
<p>Here, <span class="math inline">\(\delta_h\)</span> is the indicator-specific within-population degree-ratio adjustment: it captures whether domestic workers with indicator <span class="math inline">\(h\)</span> have, on average, more or fewer within-domestic-worker network ties than domestic workers overall. Values of <span class="math inline">\(\delta_h &lt; 1\)</span> imply that workers with indicator <span class="math inline">\(h\)</span> are less connected within the domestic-worker network and would therefore be under-represented in alter reports. The parameter <span class="math inline">\(\tau_h\)</span> is the indicator-specific true-positive or visibility rate: the probability that an alter who truly has indicator <span class="math inline">\(h\)</span> is recognised and reported by the respondent as having that indicator. Values of <span class="math inline">\(\tau_h &lt; 1\)</span> capture under-reporting due to stigma, concealment, limited observability, or social distance.</p>
<p>Because both the reporting frame and the alter universe are restricted to domestic workers, <span class="math inline">\(\delta_h\)</span> should not be read as a general-population-to-hidden-population degree ratio. It is instead a within-domestic-worker correction for differential network visibility of workers with indicator <span class="math inline">\(h\)</span>. Similarly, <span class="math inline">\(\tau_h\)</span> captures peer-tie visibility for each exploitation indicator. This distinction is central to the paper’s visibility-gradient diagnostic: when RDS own-experience estimates exceed NSUM alter-report estimates, the difference is interpreted not simply as disagreement between methods, but as evidence that some exploitation behaviours are less visible in peer networks than others (<a href="#sec-divergence" class="quarto-xref">Section&nbsp;5.3</a>).</p>
<p>Our headline NSUM result is the continuous-<span class="math inline">\(\tau\)</span> sweep: for each indicator, we report prevalence as a function of <span class="math inline">\(\tau_h \in [0.40, 1.00]\)</span>, in increments of 0.05, with <span class="math inline">\(\delta_h\)</span> fixed at 0.9 and bootstrap 95% confidence intervals at each value (Appendix Figure D.4). For comparison with the discrete-tier NSUM literature <span class="citation" data-cites="kill98-social malt15-estimating feeh16-generalizing">(<a href="#ref-feeh16-generalizing" role="doc-biblioref">Feehan &amp; Salganik, 2016</a>; <a href="#ref-kill98-social" role="doc-biblioref">Killworth et al., 1998</a>; <a href="#ref-malt15-estimating" role="doc-biblioref">Maltiel et al., 2015</a>)</span>, we also report three reference scenarios: Unadjusted <span class="math inline">\((\delta_h = 1.0, \tau_h = 1.0\)</span>), Moderate <span class="math inline">\((\delta_h = 0.9, \tau_h = 0.85)\)</span>, and Conservative <span class="math inline">\((\delta_h = 0.8, \tau_h = 0.70)\)</span>. These scenarios are presented as reference points on the continuous sensitivity curve rather than as separately identified estimates of <span class="math inline">\(\delta_h\)</span> or <span class="math inline">\(\tau_h\)</span>.</p>
</section>
<section id="sec-comparative-rationale" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-comparative-rationale"><span class="header-section-number">3.5</span> Comparative Rationale: Ego-Based vs.&nbsp;Alter-Based Inference</h2>
<p>RDS and NSUM both exploit social network structures but use fundamentally different information for inference. RDS uses ego-based information: respondents report their own characteristics and network degree, which are combined with recruitment wave to adjust for unequal inclusion probabilities. The underlying logic is that individuals with larger networks are more likely to be recruited, creating bias toward highly connected respondents. RDS estimators explicitly correct for this by weighting observations according to network degree and recruitment path.</p>
<p>NSUM uses alter-based information – respondents serve as informants about the wider hidden population, reporting how many people they know with specific traits. These reports are scaled up using assumptions about network size and visibility to infer prevalence in the broader population. NSUM does not depend on recruitment chains but instead on the accuracy of respondents’ knowledge about others in their social circles.</p>
<p>Applying both methods to the same dataset allows for triangulation across two fundamentally different inferential logics–one anchored in “who recruited whom” (RDS), the other in “how many alters fit this category” (NSUM).</p>
<p><strong>3.6 Choice of population size and the invariance of prevalence.</strong></p>
<p>For the prevalence estimates reported here, the assumed total domestic-worker population size <span class="math inline">\(N\)</span> either cancels algebraically or has a negligible finite-population effect (related to <span class="math inline">\(n/N\)</span> which is negligable here) over the range of <span class="math inline">\(N\)</span> values considered. RDS-I, RDS-II/Volz-Heckathorn, and the MBSU NSUM prevalence formulas are algebraically free of <span class="math inline">\(N\)</span>; RDS-SS and MA-RDS contain <span class="math inline">\(N\)</span> only through finite-population corrections whose magnitude scales with <span class="math inline">\(n/N\)</span>. At <span class="math inline">\(n = 85\)</span> our sampling fraction is at most 0.17% (for <span class="math inline">\(N = 50{,}000\)</span>) and as low as 0.005% (for <span class="math inline">\(N = 1{,}740{,}000\)</span>), all well below the conventional 5% threshold at which finite-population corrections become non-negligible. Headline estimates use <span class="math inline">\(N = 980{,}000\)</span> (the EU baseline); the MA-RDS Bayesian analysis uses <span class="math inline">\(N = 50{,}000\)</span> for computational tractability. Cached estimates across all four values agree to within bootstrap noise; full algebraic derivation and empirical confirmation are in the Appendix, Section D.1 (Population Size and the Invariance of Prevalence).</p>
</section>
<section id="sec-bootstrap" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-bootstrap"><span class="header-section-number">3.6</span> Bootstrap and Sensitivity Procedures</h2>
<p>To appropriately characterise uncertainty in NSUM estimates, we implement a three-step bootstrap procedure. This approach resamples respondents, their reported alters, and the exploitation classifications simultaneously, thereby capturing uncertainty at each stage of the inference process. This procedure provides more realistic confidence intervals than those generated by conventional variance estimators, particularly for small samples such as ours. Details of the bootstrap implementation and diagnostic checks are provided in the Appendix, Section C. Several of the estimation procedures implemented here adopt Bayesian or model-assisted frameworks, which are particularly appropriate for modest sample sizes because they incorporate uncertainty directly into the estimation process <span class="citation" data-cites="gile18-methods">(<a href="#ref-gile18-methods" role="doc-biblioref">Gile et al., 2018</a>)</span>. Our custom neighbourhood bootstrap procedure similarly quantifies uncertainty by repeatedly resampling ego and alter information, producing empirically grounded confidence intervals rather than relying on asymptotic approximations that assume large samples.</p>
<p>For RDS estimators, we employ neighborhood bootstrap methods that preserve the network structure while resampling <span class="citation" data-cites="yauc22-neighborhood">(<a href="#ref-yauc22-neighborhood" role="doc-biblioref">Yauck et al., 2022</a>)</span>. Sensitivity analyses examine robustness to population size assumptions (50K, 100K, 980K, 1.74M) and NSUM adjustment factor values. Full results are reported in the Appendix.</p>
</section>
</section>
<section id="sec-results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<p>We present results in five subsections. <a href="#sec-descriptive" class="quarto-xref">Section&nbsp;4.1</a> describes the analytical sample. Sections <a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a> and <a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a> report the preferred prevalence estimates for the continuous composite risk index and the five binary ILO-aligned indicators respectively. For binary indicators, the preferred estimator is RDS-SS (Gile’s Successive Sampling) with neighbourhood-bootstrap 95% confidence intervals; for the composite risk index, also RDS-SS, because the Bayesian Model-Assisted estimator does not converge to a useful posterior on continuous outcomes at our sample size (<a href="#sec-estimation-framework" class="quarto-xref">Section&nbsp;3.4</a>). The preferred NSUM result is the continuous-<span class="math inline">\(\tau\)</span> sweep over <span class="math inline">\(\tau \in [0.40, 1.00]\)</span> with <span class="math inline">\(\delta\)</span> fixed at 0.9 (<a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a>; Appendix Figure D.4); the Moderate discrete-tier point estimate (<span class="math inline">\(\delta = 0.9\)</span>, <span class="math inline">\(\tau = 0.85\)</span>) is reported alongside as a reference scenario for direct comparison with the discrete-tier NSUM literature. <a href="#sec-supporting-estimates" class="quarto-xref">Section&nbsp;4.4</a> reports supporting estimates – Bayesian Model-Assisted estimates for the five binary indicators, alternative RDS estimators (RDS-I, RDS-II), and NSUM under alternative adjustment-factor scenarios – included for comparison and to support the robustness claims in <a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a>. <a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a> summarises the sensitivity analyses, with full details in the Appendix.</p>
<p>The estimates reported below are exploratory population-adjusted estimates for the RDS-reachable population of UK migrant domestic workers connected to the participating civil-society networks (primarily Kalayaan and the Latin American Women’s Rights Service). They should not be read as definitive national prevalence figures for all UK migrant domestic workers. The reported quantities in <a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a> target different population quantities (<a href="#sec-estimation-framework" class="quarto-xref">Section&nbsp;3.4</a>), so absolute levels also differ by estimator in interpretable ways.</p>
<section id="sec-descriptive" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-descriptive"><span class="header-section-number">4.1</span> Descriptive Overview</h2>
<p>Sample demographics are presented in <a href="#tbl-demographics" class="quarto-xref">Table&nbsp;2</a>; sample composition by nationality cluster and recruitment wave in <a href="#tbl-sample-chars" class="quarto-xref">Table&nbsp;3</a>; the recruitment network in <a href="#fig-recruitment" class="quarto-xref">Figure&nbsp;1</a>. 97 respondents completed the survey; 85 with non-zero network degree were included in RDS analysis. The analytical sample is 93% transnational migrant, 98% female, 76% Filipino, with 49% aged 45+ and 47% self-employed.</p>
<section id="sec-rds-diagnostics" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="sec-rds-diagnostics"><span class="header-section-number">4.1.1</span> RDS Sampling Diagnostics</h3>
<p>Because the RDS estimators reported below rely on assumptions about chain propagation, degree homogeneity within seed groups, and reaching equilibrium across recruitment waves, we report the key sampling diagnostics here in the main text rather than in the supplement. The diagnostics are summarised in <a href="#tbl-rds-diagnostics" class="quarto-xref">Table&nbsp;5</a> and visualised in <a href="#fig-rds-diagnostics" class="quarto-xref">Figure&nbsp;2</a>; <a href="#fig-recruitment" class="quarto-xref">Figure&nbsp;1</a> (above) shows the full recruitment graph.</p>
<div id="tbl-rds-diagnostics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rds-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: RDS sampling diagnostics for the analytical sample (n = 85). Computed from the anonymised processed analysis dataset; replication code is available in the OSF repository. See <a href="#sec-rds-diagnostics" class="quarto-xref">Section&nbsp;4.1.1</a> below and the Appendix (Section D) for the full set. Source: Authors’ construction.
</figcaption>
<div aria-describedby="tbl-rds-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Diagnostic | Value | Interpretation</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-rds-diagnostics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rds-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/rds_diagnostics.png" class="img-fluid figure-img" style="width:6in">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rds-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: RDS sampling-design diagnostics. Left: distribution of respondents by recruitment wave; majority are seeds (wave 0) with only 6 of 85 respondents reaching wave 3 or higher. Middle: distribution of recruitment-chain lengths by root seed; 30 of 46 chains are singletons (seed with no recruits), and one chain (seed #55, length 12) accounts for a disproportionate share of wave-2+ respondents. Right: distribution of reported network size (q13), showing strong right skew (median 5, mean 8.9, max 105). Source: Authors’ construction. Computed from the anonymised processed analysis dataset; replication code is available in the OSF repository.
</figcaption>
</figure>
</div>
<p>Three features warrant acknowledgement. The high share of seeds (54%) and low share of wave-3+ respondents (7%) mean the sample is closer to a <em>civil-society-mediated web-RDS sample with network adjustment</em> than to a fully propagated RDS sample; the standard RDS assumption of approximately stationary sampling distribution is therefore only partially satisfied. The chain-length distribution is also highly skewed: one chain (seed #55, length 12) accounts for roughly a third of wave-2+ respondents, and a leave-one-out sensitivity excluding that chain (reported in Appendix Section D.8) does not change the rank ordering of indicators. Finally, with 76% of the sample Filipino, most chains are within-Filipino, so prevalence estimates are best read as estimates for the Filipino-dominated civil-society-reachable subpopulation rather than for all UK migrant domestic workers. The practical implication for the headline numbers is that RDS-SS, MA-RDS, and the composite index should all be read with this constrained sampling structure in view; the RDS-I vs RDS-SS comparison reported in <a href="#sec-supporting-estimates" class="quarto-xref">Section&nbsp;4.4</a> quantifies how much the standard equilibrium assumption matters (RDS-I runs 5–15 percentage points higher, with the gap larger where seed-cluster homophily is strongest).</p>
</section>
</section>
<section id="sec-composite-results" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-composite-results"><span class="header-section-number">4.2</span> Continuous Risk Index: RDS-SS Estimates</h2>
<p>One of the central contributions of this study is the introduction of a continuous risk index measuring degree of exposure to labour exploitation. The index is constructed from all eleven ILO indicators of forced labour. Each of the eleven ILO indicator categories contributes equally to the composite (maximum 0.09 per category, giving a total maximum score of 0.99); within a category, weight is distributed evenly across the sub-questions used to code it. The composite is therefore uniform-weighted at the ILO-category level and does not itself impose the medium/strong severity ordering, though we use that ordering (Section 2) to organise reporting and interpretation. The weight-perturbation robustness check reported in <a href="#sec-weights-sensitivity" class="quarto-xref">Section&nbsp;5.5</a> confirms that the ranking of respondents by composite risk is essentially invariant to the specific weight choice. NRM-referral history and payment below the national living wage are reported as separate binary evidentiary flags and are not part of the composite (<a href="#sec-survey-instrument" class="quarto-xref">Section&nbsp;3.2</a>, <a href="#tbl-indicator-mapping" class="quarto-xref">Table&nbsp;1</a>; full per-category weights in Appendix Table A.1). Rather than treating exploitation as a dichotomy, the risk index conceptualises every domestic worker as facing some degree of potential exploitation, varying continuously in intensity from low to high.</p>
<p>The preferred population-adjusted estimate uses Gile’s Successive Sampling (RDS-SS) Horvitz-Thompson estimator with neighbourhood bootstrap. The estimated mean risk index for the RDS-reachable population of UK migrant domestic workers connected to the participating civil-society networks is 37.0% of the theoretical maximum (95% CI 30.9–44.0%), very close to the observed sample mean of 37.5% – indicating that the RDS-SS finite-population adjustment makes only a small correction at our sampling fraction. We report RDS-SS rather than the Bayesian Model-Assisted estimator for the composite index because, as noted in <a href="#sec-estimation-framework" class="quarto-xref">Section&nbsp;3.4</a>, MA-RDS does not converge to a useful posterior on continuous traits at this sample size; for completeness <a href="#fig-composite" class="quarto-xref">Figure&nbsp;3</a> shows the MA estimate alongside the RDS-SS and sample estimates, with the wide MA credible interval making the limitation visible.</p>
<div id="fig-composite" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-composite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig3_composite_risk.png" class="img-fluid figure-img" style="width:6in">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-composite-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Composite Risk Index: Comparison of Three Estimators. Mean composite risk index across the observed RDS sample (descriptive; n=85), the RDS-SS adjusted estimator (Gile’s Successive Sampling with bootstrap 95% CI), and the Bayesian Model-Assisted (MA) estimator (with 95% credible interval). The wide MA credible interval reflects known limitations of model-assisted inference for continuous outcomes; the RDS-SS estimate is the more reliable population-adjusted figure. Source: Authors’ own work.
</figcaption>
</figure>
</div>
</section>
<section id="sec-binary-results" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-binary-results"><span class="header-section-number">4.3</span> Binary Exploitation Indicators: Preferred Prevalence Estimates</h2>
<p><a href="#tbl-preferred-estimates" class="quarto-xref">Table&nbsp;6</a> reports the preferred prevalence estimates for each of the five binary ILO-aligned indicators in the RDS-reachable population, presenting RDS-SS (ego-based) and MBSU NSUM Moderate (alter-based) estimates side by side. Appendix Figure D.2 shows the RDS-SS and RDS-I estimates with per-method bootstrap CIs for visual comparison (the preferred binary-indicator estimator is RDS-SS).</p>
<p>Prevalence is high for most indicators in this hidden population. RDS-SS estimates range from 35.4% for document withholding to 84.2% for excessive working hours; MBSU Moderate NSUM estimates range from 1.08% (document withholding) to 2.98% (excessive hours). The order-of-magnitude difference between RDS and NSUM is consistent with a visibility gradient: ego-based RDS reports capture what the respondent personally experienced, alter-based NSUM reports capture what other domestic workers can see. For behaviours that occur behind closed doors, the gap between own-experience and network-visible reports is large, and the divergence between RDS and NSUM estimates is correspondingly large (<a href="#sec-divergence" class="quarto-xref">Section&nbsp;5.3</a> develops the diagnostic interpretation in detail; the gap also reflects differences in estimand, sampling frame, transmission bias, and the unknown true-positive rate). Within methods, the ordering of indicators by prevalence is remarkably stable: excessive working hours consistently the highest, followed by threats and abuse and pay-related issues, with document withholding the lowest. This consistency across methods, even where absolute levels differ, is a robustness signal for the ordering of the indicators.</p>
<div id="tbl-preferred-estimates" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-preferred-estimates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Preferred prevalence estimates for the five binary ILO-aligned indicators (UK migrant domestic workers connected to participating civil-society networks; <span class="math inline">\(N\)</span> = 980,000 assumed for absolute counts). RDS-SS columns from neighbourhood-bootstrap 95% CIs (<span class="math inline">\(B\)</span> = 1000); MBSU NSUM (Moderate: <span class="math inline">\(\delta\)</span> = 0.9, <span class="math inline">\(\tau\)</span> = 0.85) columns from neighbourhood-bootstrap 95% CIs. Source: Authors’ own work.
</figcaption>
<div aria-describedby="tbl-preferred-estimates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 25%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Indicator</strong></th>
<th><strong>RDS-SS (95% CI)</strong></th>
<th><strong>MBSU NSUM (Moderate) (95% CI)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Document withholding</td>
<td>35.4% (21.1–49.8%)</td>
<td>1.08% (0.30–3.13%)</td>
</tr>
<tr class="even">
<td>Threats and abuse</td>
<td>56.9% (42.3–72.1%)</td>
<td>2.69% (1.86–5.86%)</td>
</tr>
<tr class="odd">
<td>Pay-related issues</td>
<td>51.6% (36.5–65.5%)</td>
<td>2.88% (1.90–5.68%)</td>
</tr>
<tr class="even">
<td>Excessive working hours</td>
<td>84.2% (72.2–93.6%)</td>
<td>2.98% (1.84–5.51%)</td>
</tr>
<tr class="odd">
<td>Limited access to help</td>
<td>60.6% (45.2–74.1%)</td>
<td>2.03% (0.67–4.88%)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-ma-binary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ma-binary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig4_ma_binary.png" class="img-fluid figure-img" style="width:6in">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ma-binary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Model-Assisted Estimates of Exploitation Prevalence. Population prevalence estimates with 95% credible intervals for each exploitation indicator, ordered by prevalence magnitude. Posterior intervals are from Bayesian Model-Assisted inference <span class="citation" data-cites="gile15-network">(<a href="#ref-gile15-network" role="doc-biblioref">Gile &amp; Handcock, 2015</a>)</span> at N=50,000 with seed.selection=‘degree’. Source: Authors’ own work.
</figcaption>
</figure>
</div>
</section>
<section id="sec-supporting-estimates" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-supporting-estimates"><span class="header-section-number">4.4</span> Supporting Estimates and Method Comparison</h2>
<p>Three additional families of estimates are reported in full in the Appendix (Section D) for transparency and robustness: (a) The five Bayesian Model-Assisted (MA-RDS) posterior means (Appendix Table D.1) range from 34.1% for document withholding to 84.0% for excessive working hours, reproducing the RDS-SS ordering in <a href="#tbl-preferred-estimates" class="quarto-xref">Table&nbsp;6</a>. (b) Direct comparison of RDS-I and RDS-SS estimators for each indicator with per-method bootstrap 95% CIs (Appendix Table D.3); RDS-I runs systematically higher than RDS-SS by 5–15 percentage points, consistent with the standard finding that RDS-I is sensitive to seed dependence and performs poorly at the small sample sizes and shallow chain depths characteristic of our design (<a href="#sec-rds-diagnostics" class="quarto-xref">Section&nbsp;4.1.1</a>). (c) NSUM under the three discrete adjustment-factor tiers (Unadjusted, Moderate, Conservative; Appendix Table D.4), presented for direct comparison with the discrete-tier NSUM literature. The substantive headline NSUM result is the continuous-<span class="math inline">\(\tau\)</span> sweep reported in <a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a>.</p>
</section>
<section id="sec-sensitivity" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-sensitivity"><span class="header-section-number">4.5</span> Sensitivity and Robustness</h2>
<p>Three sensitivity analyses are reported in full in the Appendix. First, the continuous-<span class="math inline">\(\tau\)</span> NSUM sweep (Appendix Figure D.4) shows MBSU prevalence monotonically increasing as <span class="math inline">\(\tau\)</span> decreases; the increase is modest across the plausible range <span class="math inline">\(\tau \in [0.7, 1.0]\)</span> and substantial only at low <span class="math inline">\(\tau \le 0.5\)</span>. This continuous picture supersedes the discrete-tier comparison (<a href="#sec-supporting-estimates" class="quarto-xref">Section&nbsp;4.4</a>) for substantive inference about how visibility assumptions affect estimates.</p>
<p>Second, the MA-RDS seed-selection sensitivity (Appendix Figure D.1) shows that the Bayesian MA posterior estimates are insensitive to the choice of seed-selection method (degree, random, sample) at our sample size – different chains converge to the same posterior, confirming model robustness to initialisation.</p>
<p>Third, cross-indicator and cross-method consistency: across the five indicators and the four main estimators (RDS-I, RDS-SS, MA-RDS, MBSU NSUM Moderate), the rank-ordering of indicators by prevalence is stable. Excessive working hours is consistently highest, followed by threats and abuse and pay-related issues, with document withholding the lowest. Absolute prevalence levels vary by method but the substantive picture – which exploitation behaviours are most common, which least – does not.</p>
</section>
</section>
<section id="sec-discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<section id="sec-summary" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-summary"><span class="header-section-number">5.1</span> Summary of Findings</h2>
<p>Across five ILO-aligned binary indicators measured on a respondent-driven sample of 85 UK migrant domestic workers, RDS-SS Horvitz-Thompson prevalence estimates range from 35.4% for document withholding (95% CI 21.1–49.8%) to 84.2% for excessive working hours (95% CI 72.2–93.6%); a composite continuous risk index covering all eleven indicator dimensions gives an estimated mean exploitation intensity of 37.0% (95% CI 30.9–44.0%). MBSU Moderate NSUM estimates of the same five binary indicators range from 1.08% (document withholding) to 2.98% (excessive hours), an order-of-magnitude lower than the RDS-SS figures. The within-method ordering of indicators is consistent across methods: excessive working hours always highest, followed by threats and abuse and pay-related issues, with document withholding always lowest. This consistency, alongside the order-of-magnitude gap between ego-based (RDS) and alter-based (NSUM) estimates, is the central empirical finding of the paper. The remainder of this section interprets both the absolute estimates and the inter-method divergence.</p>
</section>
<section id="sec-contributions" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-contributions"><span class="header-section-number">5.2</span> Methodological Reflections and Contributions</h2>
<p>This paper makes two contributions to the measurement of modern slavery among hidden populations. First, we apply RDS and NSUM to the same matched survey instrument in what is, to our knowledge, among the first applications of this dual design in any developed-economy setting for the measurement of forced-labour and modern-slavery indicators; the design supports direct comparison of ego-based and alter-based estimates on a like-for-like indicator set without claiming they target the same population quantity (<a href="#sec-estimation-framework" class="quarto-xref">Section&nbsp;3.4</a>, <a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a>). Second, we operationalise modern slavery as a graded formative indicator framework rather than a binary condition, supporting both indicator-level prevalence estimates and an eleven-indicator formative additive composite risk index for ordinal severity gradation.</p>
<p>The combined contributions are: (i) operationalising exploitation both as a five-indicator binary set (<a href="#sec-binary-results" class="quarto-xref">Section&nbsp;4.3</a>) and as a formative additive composite spanning all eleven ILO categories (<a href="#sec-composite-results" class="quarto-xref">Section&nbsp;4.2</a>); (ii) applying RDS and NSUM to the same instrument, exposing the visibility gradient where the two methods diverge (<a href="#sec-divergence" class="quarto-xref">Section&nbsp;5.3</a>); (iii) implementing a three-step bootstrap procedure for NSUM that resamples respondents, alters, and exploitation classifications in succession; and (iv) demonstrating feasibility in a stigmatised and under-researched population mediated by civil-society partners, with the methodology generalisable to other hidden populations relevant to SDG 8.7 monitoring (<a href="#sec-policy" class="quarto-xref">Section&nbsp;5.6</a>).</p>
<p>The paper’s measurement strategy can be evaluated against five validation channels. Content validity rests on anchoring the indicator set in the ILO framework of forced labour <span class="citation" data-cites="ILO11-indicators hard24-ilo int25-ilo">(<a href="#ref-ILO11-indicators" role="doc-biblioref">2012</a>, <a href="#ref-hard24-ilo" role="doc-biblioref">2024</a>, <a href="#ref-int25-ilo" role="doc-biblioref">2025</a>)</span>, with the indicator-to-survey-question mapping in <a href="#tbl-indicator-mapping" class="quarto-xref">Table&nbsp;1</a>. Face validity rests on co-development of the survey instrument with the three participating civil-society organisations (Kalayaan, Voice of Domestic Workers, LAWRS), whose case-work practice informed item wording. Convergent validity rests on the reproduction of the within-method indicator ordering across four methodologically unrelated estimators (<a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a>). Robustness rests on the composite-risk ranking being essentially weight-invariant under ±50% perturbation (Spearman <span class="math inline">\(\rho\)</span> = 0.992 ρ=0.992; <a href="#sec-weights-sensitivity" class="quarto-xref">Section&nbsp;5.5</a>) and on the headline NSUM estimates being reported as a continuous function of <span class="math inline">\(\tau\)</span> rather than a single point. Limitation: the strategy does not yet include external validation against administrative sources (NRM referrals, employment-tribunal records) — the natural next step for the broader SDG 8.7 monitoring architecture (<a href="#sec-policy" class="quarto-xref">Section&nbsp;5.6</a>).</p>
</section>
<section id="sec-divergence" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-divergence"><span class="header-section-number">5.3</span> The RDS–NSUM Divergence as Diagnostic</h2>
<p>Two related concerns are taken up here: that the reported prevalence estimates span a wide range, and that the sample size (n = 85) is small for population-level inference. The apparent “wide range” reflects three conceptually distinct sources of dispersion, each carrying different epistemic weight. Sample size operates through only one of these three sources, and on that source <span class="math inline">\(n=85\)</span> is competitive for hidden-population designs.</p>
<p><em>Across-indicator variation.</em> Within any single method, prevalence varies substantially across the five indicators – under RDS-SS, from 35.4% (document withholding) to 84.2% (excessive working hours), a 49-percentage-point spread. This is a substantive finding, not noise: severe forms of coercion (document confiscation, an ILO strong indicator in <span class="citation" data-cites="hard24-ilo">International Labour Organization (<a href="#ref-hard24-ilo" role="doc-biblioref">2024</a>)</span>) are less common in this population than less severe forms of abuse (excessive hours, an ILO medium indicator). The ordering is interpretable, matches the ILO severity ordering documented in the ILO survey-guidelines handbook <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span>, and is reproduced across methods. Collapsing this ordering into a single “wide range” headline obscures what is arguably the paper’s most policy-relevant finding: different exploitation behaviours have meaningfully different population frequencies.</p>
<p><em>Across-method variation.</em> For any single indicator, RDS and NSUM estimates differ by roughly an order of magnitude: document withholding 35.4% (RDS-SS) versus 1.08% (MBSU Moderate); excessive hours 84.2% versus 2.98%. This is the visibility-gradient diagnostic at the centre of the paper’s contribution: ego-based RDS asks what happened to you, alter-based NSUM asks what you can see happening to others, and the two answer related but different questions for behaviours that occur behind closed doors. The gap is consistent with a visibility gradient – some exploitation behaviours are readily observable by peers, others remain concealed within the household. We are cautious not to claim that the gap <em>quantifies</em> visibility, because the divergence also reflects differences in estimand (<a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a>), sampling frame, transmission bias, and the unknown true-positive rate <span class="math inline">\(\tau\)</span> (which the continuous-<span class="math inline">\(\tau\)</span> sweep in the Appendix makes explicit). Reporting RDS and NSUM side-by-side (<a href="#tbl-preferred-estimates" class="quarto-xref">Table&nbsp;6</a>) is the paper’s design choice precisely because the gap is interpretable as diagnostic evidence rather than as a single estimate of a single quantity.</p>
<p><em>Within-method, within-indicator sampling variation.</em> This is the only source that is irreducibly statistical uncertainty in the conventional sense, captured by bootstrap confidence intervals. RDS-SS within-indicator CIs span 21–30 percentage points; MBSU Moderate within-indicator CIs span 1–4 percentage points. A residual NSUM-specific component comes from the unknown <span class="math inline">\(\tau\)</span>, reported as the continuous-<span class="math inline">\(\tau\)</span> sweep in the Appendix (Section D.5, Figure D.4) rather than as a single point. Sample size operates through this third channel and only this third channel: more respondents would narrow the bootstrap CIs but would not narrow the across-indicator hierarchy (which is real) or the across-method gap (which is the diagnostic finding).</p>
<p>Three further observations support the visibility-gradient interpretation. The gap is largest for indicators we would expect to be least visible (document withholding, ego/alter ratio 33<span class="math inline">\(\times\)</span>) and smaller for more visible indicators (excessive hours: ratio 28<span class="math inline">\(\times\)</span>). The within-method ordering of indicators is stable across methodologically unrelated estimators – a robustness signal that justifies treating the indicators as distinct gradations of severity even where absolute levels differ. And the direction of the bias matches the NSUM transmission-bias literature <span class="citation" data-cites="kill98-social malt15-estimating feeh16-generalizing">(<a href="#ref-feeh16-generalizing" role="doc-biblioref">Feehan &amp; Salganik, 2016</a>; <a href="#ref-kill98-social" role="doc-biblioref">Killworth et al., 1998</a>; <a href="#ref-malt15-estimating" role="doc-biblioref">Maltiel et al., 2015</a>)</span>, which documents systematic alter under-reporting for stigmatised traits, often of an order of magnitude.</p>
<p>On sample size: n = 85 is small by household-survey standards but competitive for hidden-population studies (published RDS applications operate at 100–300; UK domestic-worker NGO samples are typically smaller and not network-recruited). The dual ego/alter design extracts more information per respondent than a household survey, yielding 170 indicator measurements per ILO category once both reports are counted before any network-weighting amplification. Chain depth is shallower than the RDS design envisaged (<a href="#sec-rds-diagnostics" class="quarto-xref">Section&nbsp;4.1.1</a>); a longer field period would help in future replications.</p>
</section>
<section id="sec-generalisability" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-generalisability"><span class="header-section-number">5.4</span> Generalisability and Indicator Coverage</h2>
<p>One may reasonably question whether estimates from a single civil-society-mediated sample can support population-level claims, and whether the five indicators we measure capture the full ILO conceptual space. Both are valid concerns and both warrant qualification of the paper’s claims rather than retreat from them.</p>
<p>On generalisability: the sample is drawn from two London-based civil-society networks (Kalayaan and the Latin American Women’s Rights Service) and is not representative of all UK migrant domestic workers, much less all hidden populations relevant to SDG 8.7. Demographics skew Filipino and Latinx, omitting substantial South Asian, East African, and Eastern European communities not reached by the participating networks. What the paper demonstrates is methodological feasibility on a hard realistic case and a set of specific estimates for that sample; the methodology generalises but the specific prevalence numbers should not be extrapolated beyond this sample.</p>
<p>On indicator coverage: the five binary indicators bundle nine of the eleven ILO categories (<a href="#sec-survey-instrument" class="quarto-xref">Section&nbsp;3.2</a>, <a href="#tbl-indicator-mapping" class="quarto-xref">Table&nbsp;1</a>) — threats and abuse combines two ILO categories (intimidation/threats and physical and sexual violence), pay-related issues combines two (wage withholding and debt bondage), limited access to help combines two (restriction of movement and isolation), document withholding and excessive working hours each map to a single ILO category, and threats and abuse also captures part of ILO Category 10 (abusive working and living conditions) through Q48.</p>
<p>Putting these qualifications together, what does this design licence the paper to claim? The four estimators (RDS-SS, MA-RDS, MBSU Moderate NSUM, the composite risk index) each yield point estimates, but each targets a <em>different</em> population quantity (<a href="#tbl-estimands" class="quarto-xref">Table&nbsp;4</a>): own-experience prevalence, network-visible prevalence, and severity score. No single estimate is identified <em>as</em> ‘the prevalence of forced labour among UK domestic workers’, because that label spans both ego-based and alter-based quantities at once. If RDS over-samples respondents with first-hand experience and NSUM under-detects concealed exploitation, the true prevalence for any given indicator plausibly lies between the two reports – but the precise location depends on assumptions about visibility, sampling, and reporting that the data cannot pin down. We treat this as a working hypothesis, not an identification result. The design does licence (a) a conservative reference scenario under the stated MBSU assumptions (MBSU Moderate, <span class="math inline">\(\delta = 0.9\)</span>, <span class="math inline">\(\tau = 0.85\)</span>, sits on the conservative side of the continuous-<span class="math inline">\(\tau\)</span> sweep in <a href="#sec-sensitivity" class="quarto-xref">Section&nbsp;4.5</a>); (b) a credible characterisation of relative incidence (from RDS) and the indicator severity hierarchy (from cross-method robustness); and (c) a visibility diagnostic for network-mediated outreach (<a href="#sec-policy" class="quarto-xref">Section&nbsp;5.6</a>).</p>
</section>
<section id="sec-weights-sensitivity" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-weights-sensitivity"><span class="header-section-number">5.5</span> Composite Risk Index: Construction and Weight Sensitivity</h2>
<p>A further question is whether the composite risk index is sensitive to the specific weights on its eleven sub-indicators (already documented in <a href="#sec-survey-instrument" class="quarto-xref">Section&nbsp;3.2</a> and the Appendix, Section A). We address this with a weight-perturbation sensitivity analysis: each weight was multiplied by an independent uniform factor in <span class="math inline">\([0.5, 1.5]\)</span> (i.e., <span class="math inline">\(\pm 50\%\)</span> perturbation), the composite was recomputed under the perturbed weights, and the resulting respondent ranking was compared to baseline. We repeated this for 5,000 independent perturbations.</p>
<p>The ranking of respondents by composite-risk is essentially weight-invariant. Mean Spearman rank correlation between the perturbed and baseline composites was <span class="math inline">\(\rho = 0.992\)</span> (95% range across perturbations: 0.985–0.997), with the worst-case <span class="math inline">\(\rho\)</span> across all 5,000 draws being 0.974. The 97.5% interval of perturbed composites that fell in the same top quartile as the baseline composite was 92–100%, with a mean of 97.5%. Even under a more aggressive ±75% perturbation, Spearman <span class="math inline">\(\rho\)</span> remained above 0.944 in the worst case across 5,000 draws and the top-quartile preservation averaged 94.4%. We conclude that the substantive conclusions of the composite-risk analysis – which respondents are at highest risk, the population mean of 37.0%, and the rank-ordering used for downstream analyses – do not depend on the specific weighting choice within any plausible alternative parameterisation. Full perturbation results are reported in the Appendix.</p>
</section>
<section id="sec-policy" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-policy"><span class="header-section-number">5.6</span> Policy Implications and SDG 8.7 Monitoring</h2>
<p>The dual RDS–NSUM design and the visibility-gradient diagnostic are themselves policy-useful outputs for SDG 8.7 monitoring. Target 8.7 commits signatory states to “take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking” by 2030, with monitoring requiring credible prevalence estimation for populations largely invisible to official statistics. The methodology demonstrated here – matched ego-alter instruments fielded through civil-society partnerships, estimated with parallel RDS and NSUM frameworks, and reported with explicit visibility-adjustment sensitivity – is replicable for other hidden populations relevant to 8.7 monitoring (undocumented agricultural workers, sex workers, kafala-system migrants). The specific numerical estimates here apply only to UK migrant domestic workers; the design is the contribution.</p>
<p>The visibility-gradient diagnostic also has direct programme-design implications. Network-mediated outreach (peer referral, civil-society partnership, warm handover) can only reach behaviours visible across network ties. Our findings suggest excessive working hours is well-suited to such outreach (small ego–alter gap), whereas document withholding is largely invisible across ties (largest gap) and will require different designs – embassy or institutional intake screening rather than peer outreach. The dual-method design therefore not only estimates prevalence but also helps calibrate identification strategy to the visibility profile of the behaviour.</p>
<p>Future work should extend the methodology to web-RDS at scale and integrate with administrative data sources (NRM referrals, immigration enforcement data subject to firewall safeguards, employment-tribunal records) for triangulation against complementary data streams.</p>
</section>
</section>
<section id="sec-conclusion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion</h1>
<p>This paper applies respondent-driven sampling and the network scale-up method to the same matched survey instrument — among the first such applications in any developed-economy study of forced-labour and modern-slavery indicators — using a sample of 85 UK migrant domestic workers recruited through three civil-society partnerships. The paper’s broader contribution is best read as developing and demonstrating a defensible social-indicator measurement strategy for hidden-population exploitation rather than as producing a definitive national prevalence estimate. Specifically, the dual RDS–NSUM design produces two complementary estimands; where they diverge, the gap is diagnostic evidence about the visibility gradient of exploitation behaviours within workers’ personal networks. Second, we operationalise modern slavery as a graded formative indicator framework rather than a binary condition, supporting both indicator-level prevalence estimates and a continuous formative additive composite risk index that gives equal weight to each of the ILO’s eleven indicators of forced labour and is organised for reporting by the ILO’s medium/strong severity ordering <span class="citation" data-cites="hard24-ilo">(<a href="#ref-hard24-ilo" role="doc-biblioref">International Labour Organization, 2024</a>)</span>.</p>
<p>The central empirical finding is the order-of-magnitude gap between ego-based (RDS) and alter-based (NSUM) estimates: for document withholding, RDS-SS estimates 35.4% prevalence vs MBSU Moderate NSUM 1.08%; for excessive working hours, 84.2% vs 2.98%. The gap is consistent with a visibility gradient across exploitation behaviours and provides diagnostic evidence about which behaviours are observable across network ties and which are not; it also reflects differences in estimand, sampling frame, and transmission bias (<a href="#sec-divergence" class="quarto-xref">Section&nbsp;5.3</a>). The policy implication is that network-mediated outreach can credibly reach exploitation behaviours visible across ties but requires complementary designs for those that are not (<a href="#sec-policy" class="quarto-xref">Section&nbsp;5.6</a>).</p>
<p>The dual-method design demonstrated here is replicable. The matched ego-alter survey instrument, parallel RDS and NSUM estimation framework, and explicit visibility-adjustment sensitivity reporting can be applied to other hidden populations relevant to SDG Target 8.7 monitoring — undocumented agricultural workers, sex workers, kafala-system migrants — and any population for which official statistics are silent.</p>
</section>
<section id="sec-declarations" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Declarations</h1>
<p><strong>Funding.</strong> CE received funding from the University of Nottingham under its Nottingham Research Fellowship scheme.</p>
<p><strong>Competing interests.</strong> The authors have no competing interests to declare.</p>
<p><strong>Ethics approval and consent to participate.</strong> The data collection that underpins the analysis presented in this paper was given favourable ethical approval by the lead author’s School Research Ethics Committee in January 2023 (Ethics Review Application number 202223021). All participants were informed about the aims of the study, provided informed consent, and were assured that participation was voluntary and confidential.</p>
<p><strong>Data availability.</strong> Anonymised respondent-level data and all analysis code are available at the project’s Open Science Framework mirror: <a href="https://osf.io/vf5yb/overview?view_only=becc2db3b49c4b258015b648867bf208" class="uri">https://osf.io/vf5yb/overview?view_only=becc2db3b49c4b258015b648867bf208</a>. The underlying GitHub repository is currently private and will be made public on acceptance.</p>
<p><strong>Use of large language models.</strong> The authors used a large language model assistant (Anthropic Claude) for textual editing and for code-review support during R script development. All final analysis decisions, statistical interpretations, and prose are the authors’ own. No generative models were used to simulate, augment, or fabricate data. This disclosure follows the Springer Nature editorial guidance on the use of generative AI tools in scholarly work.</p>
<p><strong>Authors’ contributions.</strong> CE designed and collected data; SM performed analysis. Both contributed to the writing of the document.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-bern09-broken" class="csl-entry" role="listitem">
Bernhardt, A., Milkman, R. T., &amp; N. (2009). <em>Broken laws, unprotected workers: <span>Violations</span> of employment and labor laws in america’s cities</em> [UCLA IRLE Report.].
</div>
<div id="ref-feeh16-generalizing" class="csl-entry" role="listitem">
Feehan, D. M., &amp; Salganik, M. J. (2016). Generalizing the <span>Network Scale-Up Method</span>: <span>A New Estimator</span> for the <span>Size</span> of <span>Hidden Populations</span>. <em>Sociological Methodology</em>, <em>46</em>(1), 153–186.
</div>
<div id="ref-gile11-improved" class="csl-entry" role="listitem">
Gile, K. J. (2011). Improved <span>Inference</span> for <span>Respondent-Driven Sampling Data With Application</span> to <span>HIV Prevalence Estimation</span>. <em>Journal of the American Statistical Association</em>, <em>106</em>(493), 135–146. <a href="https://doi.org/10.1198/jasa.2011.ap09475">https://doi.org/10.1198/jasa.2011.ap09475</a>
</div>
<div id="ref-gile18-methods" class="csl-entry" role="listitem">
Gile, K. J., Beaudry, I. S., Handcock, M. S., &amp; Ott, M. Q. (2018). Methods for inference from respondent-driven sampling data. <em>Annual Review of Statistics and Its Application</em>, <em>5</em>(1), 65–93. <a href="https://doi.org/10.1146/annurev-statistics-031017-100704">https://doi.org/10.1146/annurev-statistics-031017-100704</a>
</div>
<div id="ref-gile10-respondentdriven" class="csl-entry" role="listitem">
Gile, K. J., &amp; Handcock, M. S. (2010). Respondent-<span>Driven Sampling</span>: <span>An Assessment</span> of <span>Current Methodology</span>. <em>Sociological Methodology</em>, <em>40</em>, 285–327.
</div>
<div id="ref-gile15-network" class="csl-entry" role="listitem">
Gile, K. J., &amp; Handcock, M. S. (2015). Network model-assisted inference from respondent-driven sampling data. <em>Journal of the Royal Statistical Society: Series A (Statistics in Society)</em>, <em>178</em>(3), 619–639. <a href="https://doi.org/10.1111/rssa.12091">https://doi.org/10.1111/rssa.12091</a>
</div>
<div id="ref-goel10-assessing" class="csl-entry" role="listitem">
Goel, S., &amp; Salganik, M. J. (2010). Assessing respondent-driven sampling. <em>Proceedings of the National Academy of Sciences</em>, <em>107</em>(15), 6743–6747. <a href="https://doi.org/10.1073/pnas.1000261107">https://doi.org/10.1073/pnas.1000261107</a>
</div>
<div id="ref-hand14-estimating" class="csl-entry" role="listitem">
Handcock, M. S., Gile, K. J., &amp; Mar, C. M. (2014). Estimating hidden population size using <span>Respondent-Driven Sampling</span> data. <em>Electronic Journal of Statistics</em>, <em>8</em>(1), 1491–1521. <a href="https://doi.org/10.1214/14-EJS923">https://doi.org/10.1214/14-EJS923</a>
</div>
<div id="ref-heck97-respondentdriven" class="csl-entry" role="listitem">
Heckathorn, D. D. (1997). Respondent-driven sampling: <span>A</span> new approach to the study of hidden populations. <em>Social Problems</em>, <em>44</em>(2), 174–199. <a href="https://doi.org/10.2307/3096941">https://doi.org/10.2307/3096941</a>
</div>
<div id="ref-heck11-comment" class="csl-entry" role="listitem">
Heckathorn, D. D. (2011). Comment: <span>Snowball</span> versus respondent-driven sampling. <em>Sociological Methodology</em>, <em>41</em>(1), 355–366.
</div>
<div id="ref-hick25-human" class="csl-entry" role="listitem">
Hickman, S., Lopez-Jauffret, C., Fahy, &amp; Masick, V. (2025). <em>Human <span>Trafficking Prevalence Estimation Feasibility Study</span></em> (This Project Was Supported by Cooperative Agreement No. 2019-85 CX-K002 NCJ 309951). Bureau of Justice Statistics.
</div>
<div id="ref-ILO11-indicators" class="csl-entry" role="listitem">
International Labour Organization. (2012). <em>ILO indicators of forced labour</em>. International Labour Organization. <a href="https://www.ilo.org/publications/ilo-indicators-forced-labour">https://www.ilo.org/publications/ilo-indicators-forced-labour</a>
</div>
<div id="ref-hard24-ilo" class="csl-entry" role="listitem">
International Labour Organization. (2024). <em>Hard to see, harder to count handbook on forced labour surveys</em> (Third Edition). International Labour Organization. <a href="https://www.ilo.org/forcedlabour">https://www.ilo.org/forcedlabour</a>
</div>
<div id="ref-int25-ilo" class="csl-entry" role="listitem">
International Labour Organization. (2025). <em>ILO indicators of forced labour</em> [2025 revised edition]. International Labour Organization. <a href="https://www.ilo.org/forcedlabour">https://www.ilo.org/forcedlabour</a>
</div>
<div id="ref-ist20-prevalence" class="csl-entry" role="listitem">
IST Research, &amp; University of California, Los Angeles. (2020). <em>Estimating the prevalence of child sex trafficking in <span>Maharashtra</span>, <span>India</span></em> [Technical Report]. Global Fund to End Modern Slavery.
</div>
<div id="ref-jord20-overcoming" class="csl-entry" role="listitem">
Jordan, L., Chui, C. H. K., Larmar, S., &amp; O’Leary, P. (2020). Overcoming methodological challenges in prevalence studies in developing contexts with vulnerable children. <em>International Social Work</em>, <em>63</em>(3), 371–385.
</div>
<div id="ref-kala08-new" class="csl-entry" role="listitem">
Kalayaan. (2008). <em>The new bonded labour?</em>
</div>
<div id="ref-kill98-social" class="csl-entry" role="listitem">
Killworth, P. D., Johnsen, E. C., McCarty, C., Shelley, G. A., &amp; Bernard, H. R. (1998). A social network approach to estimating seroprevalence in the <span>United States</span>. <em>Social Networks</em>, <em>20</em>(1), 23–50. <a href="https://doi.org/10.1016/S0378-8733(96)00305-X">https://doi.org/10.1016/S0378-8733(96)00305-X</a>
</div>
<div id="ref-malt15-estimating" class="csl-entry" role="listitem">
Maltiel, R., Raftery, A. E., McCormick, T. H., &amp; Baraff, A. J. (2015). Estimating population size using the network scale up method. <em>The Annals of Applied Statistics</em>, <em>9</em>(3), 1247–1277. <a href="https://doi.org/10.1214/15-AOAS827">https://doi.org/10.1214/15-AOAS827</a>
</div>
<div id="ref-mant16-modern" class="csl-entry" role="listitem">
Mantouvalou, V. (2016). Modern slavery? <span>The UK</span> visa system and the exploitation of migrant domestic workers. In <em>British politics and policy at <span>LSE</span></em>.
</div>
<div id="ref-mccr12-evaluation" class="csl-entry" role="listitem">
McCreesh, N., Frost, S. D. W., Seeley, J., Katongole, J., Tarsh, M. N., Ndunguse, R., Jichi, F., Lunel, N. L., Maher, D., Johnston, L. G., Sonnenberg, P., Copas, A. J., Hayes, R. J., &amp; White, R. G. (2012). Evaluation of respondent-driven sampling. <em>Epidemiology</em>, <em>23</em>(1), 138–147. <a href="https://doi.org/10.1097/EDE.0b013e31823ac17c">https://doi.org/10.1097/EDE.0b013e31823ac17c</a>
</div>
<div id="ref-romero_blueprint_2025" class="csl-entry" role="listitem">
Romero, A., &amp; Fisher, O. (2025). <em>Blueprint for safer and fairer migration for low-paid work</em>. Focus on Labour Exploitation; Focus on Labour Exploitation. <a href="https://labourexploitation.org/app/uploads/2025/06/Flex-Report-Blueprint-for-safer-and-fairer-migration-for-low-paid-work_final_30_June-.pdf">https://labourexploitation.org/app/uploads/2025/06/Flex-Report-Blueprint-for-safer-and-fairer-migration-for-low-paid-work_final_30_June-.pdf</a>
</div>
<div id="ref-salg04-sampling" class="csl-entry" role="listitem">
Salganik, M. J., &amp; Heckathorn, D. D. (2004). Sampling and <span>Estimation</span> in <span>Hidden Populations Using Respondent-Driven Sampling</span>. <em>Sociological Methodology</em>, <em>34</em>, 193–239.
</div>
<div id="ref-schw12-prevalence" class="csl-entry" role="listitem">
Schwitters, A., Swaminathan, M., &amp; Serwadda, D. (2012). Prevalence of rape and client-initiated gender-based violence among female sex workers: <span>Kampala</span>, uganda. <em>AIDS Behaviour</em>, <em>19</em>, 68–76.
</div>
<div id="ref-serv23-closed" class="csl-entry" role="listitem">
Service, L. A. W. R. (2023). <em>Behind closed doors: <span>Experiences</span> of <span>Latin American</span> domestic workers in the <span>UK</span></em>.
</div>
<div id="ref-thompson_new_2020" class="csl-entry" role="listitem">
Thompson, S. (2020). <em>New estimates for network sampling</em>.
</div>
<div id="ref-vinc17-estimating" class="csl-entry" role="listitem">
Vincent, K., &amp; Thompson, S. (2017). Estimating population size with link-tracing sampling. <em>Journal of the American Statistical Association</em>, <em>112</em>(519), 1286–1295. <a href="https://doi.org/10.1080/01621459.2016.1212712">https://doi.org/10.1080/01621459.2016.1212712</a>
</div>
<div id="ref-volz08-probability" class="csl-entry" role="listitem">
Volz, E., &amp; Heckathorn, D. D. (2008). Probability <span>Based Estimation Theory</span> for <span>Respondent Driven Sampling</span>. <em>Journal of Official Statistics</em>, <em>24</em>(1), 79.
</div>
<div id="ref-wejn08-webbased" class="csl-entry" role="listitem">
Wejnert, C., &amp; Heckathorn, D. D. (2008). Web-based network sampling: Efficiency and efficacy of respondent-driven sampling for online research. <em>Sociological Methods &amp; Research</em>, <em>37</em>(1), 105–134.
</div>
<div id="ref-yauc22-neighborhood" class="csl-entry" role="listitem">
Yauck, M., Moodie, E. E. M., Apelian, H., Fourmigue, A., Grace, D., Hart, T. A., Lambert, G., &amp; Cox, J. (2022). Neighborhood <span>Bootstrap</span> for <span>Respondent-Driven Sampling</span>. <em>Journal of Survey Statistics and Methodology</em>, <em>10</em>(2), 419–438. <a href="https://doi.org/10.1093/jssam/smab057">https://doi.org/10.1093/jssam/smab057</a>
</div>
<div id="ref-yilm23-exploring" class="csl-entry" role="listitem">
Yilmaz, S., &amp; Emberson, C. (2023). Exploring the nature of labour exploitation among domestic workers in the <span>UK</span>. <em>Rights Lab, University of Nottingham</em>.
</div>
<div id="ref-zhang_measuring_2012" class="csl-entry" role="listitem">
Zhang, S. X. (2012). Measuring labour trafficking: A research note. <em>Crime, Law and Social Change</em>, <em>58</em>(4), 469–482. <a href="https://doi.org/10.1007/s10611-012-9363-y">https://doi.org/10.1007/s10611-012-9363-y</a>
</div>
<div id="ref-zhan19-victims" class="csl-entry" role="listitem">
Zhang, S. X., Dank, M., Vincent, K., Narayanan, P., Bharadwaj, S., &amp; Balasubramaniam, S. M. (2019). Victims without a voice: <span>Measuring</span> worst forms of child labor in the <span>Indian State</span> of <span>Bihar</span>. <em>Victims &amp; Offenders</em>, <em>14</em>(7), 832–858.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>